version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.docker/web/site.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    links:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: yii2:1.0.0
    volumes:
      - ./app:/app